print ("PRESUPUESTO MAESTRO")
print ("MAQUILADOS MEXICANOS, S.A.")
print (" ")
print ("I. PRESUPUESTO DE OPERACIÓN")
print (" ")

# TABLA 1
print ("--- PRESUPUESTO DE VENTAS ---")
print (" ")
print ("Producto CL Primer Semestre")
UVCL1 = int (input ("Unidades a Vender: "))
PVCL1 = int (input ("Precio de Venta: "))
IVCL1 = (UVCL1 * PVCL1)
print ("El Importe de Venta durante el primer semestre para el Producto CL es: ", IVCL1)
print (" ")
print ("Producto CL Segundo Semestre")
UVCL2 = int (input ("Unidades a Vender: "))
PVCL2 = int (input ("Precio de Venta: "))
IVCL2 = (UVCL2 * PVCL2)
print ("El Importe de Venta durante el segundo semestre para el Producto CL es: ", IVCL2)
print (" ")
TotalCL2016 = (IVCL1 + IVCL2)
print ("El total del Importe de Venta en el 2016 para el Producto CL es: ", TotalCL2016)
print (" ")

print ("Producto CE Primer Semestre")
UVCE1 = int (input ("Unidades a Vender: "))
PVCE1 = int (input ("Precio de Venta: "))
IVCE1 = (UVCE1 * PVCE1)
print ("El Importe de Venta durante el primer semestre para el Producto CE es: ", IVCE1)
print (" ")
print ("Producto CE Segundo Semestre")
UVCE2 = int (input ("Unidades a Vender: "))
PVCE2 = int (input ("Precio de Venta: "))
IVCE2 = (UVCE2 * PVCE2)
print ("El Importe de Venta durante el segundo semestre para el Producto CE es: ", IVCE2)
print (" ")
TotalCE2016 = (IVCE1 + IVCE2)
print ("El total del Importe de Venta en el 2016 para el Producto CE es: ", TotalCE2016)
print ("")

print ("Producto CR Primer Semestre")
UVCR1 = int (input ("Unidades a Vender: "))
PVCR1 = int (input ("Precio de Venta: "))
IVCR1 = (UVCR1 * PVCR1)
print ("El Importe de Venta durante el primer semestre para el Producto CR es: ", IVCR1)
print (" ")
print ("Producto CR Segundo Semestre")
UVCR2 = int (input ("Unidades a Vender: "))
PVCR2 = int (input ("Precio de Venta: "))
IVCR2 = (UVCR2 * PVCR2)
print ("El Importe de Venta durante el segundo semestre para el Producto CR es: ", IVCR2)
print (" ")
TotalCR2016 = (IVCR1 + IVCR2)
print ("El total del Importe de Venta en el 2016 para el Producto CR es: ", TotalCR2016)
print ("")

TVS1 = (IVCL1 + IVCE1 + IVCR1)
print ("Total de Ventas primer semestre: ", TVS1)
print (" ")
TVS2 = (IVCL2 + IVCE2 + IVCR2)
print ("Total de Ventas segundo semestre: ", TVS2)
print (" ")
TVS = (TVS1 + TVS2)
print ("Total de Ventas por ambos semestres: ", TVS)
print (" ")
print ("-" * 63)
print (" ")

#TABLA 2
print ("--- DETERMINACION DEL SALDO DE CLIENTES Y FLUJO DE ENTRADAS ---")
SaldoClientes = int (input ("Saldo de clientes 31-dic-2015: "))
print ("Ventas 2016: ",  TVS)
TotalC2016 = (SaldoClientes + TVS)
print (" ")
print ("Total de Clientes 2016: ", TotalC2016)
print (" ")
print ("Entradas de efectivo: ")
Cobranza2015 = int (input ("Por Cobranza del 2015: "))
Cobranza2016 = (TVS * .8)
print ("Por Cobranza del 2016: ", Cobranza2016)
print (" ")
TotalEntradas2016 = (Cobranza2015 + Cobranza2016)
print ("Total de Entradas 2016: ", TotalEntradas2016)
print (" ")
SaldoClientes2016 = (TotalC2016 - TotalEntradas2016)
print ("Saldo de Clientes del 2016: ", SaldoClientes2016)
print (" ")
print ("-" * 63)
print (" ")

#TABLA 3
print ("--- PRESUPUESTO DE PRODUCCION ---")
print (" ")
print ("Producto CL Primer Semestre")
UVCL1 = int (input ("Unidades a Vender: "))
IFCL1 = int (input ("Inventario Final: "))
TUCL1 = (UVCL1 + IFCL1)
print ("Total de Unidades: ", TUCL1)
IICL1 = int (input ("Inventario Inicial: "))
UPCL1 = (TUCL1 - IICL1)
print ("Unidades a Producir: ", UPCL1)
print (" ")
print ("Producto CL Segundo Semestre")
UVCL2 = int (input ("Unidades a Vender: "))
IFCL2 = int (input ("Inventario Final: "))
TUCL2 = (UVCL2 + IFCL2)
print ("Total de Unidades: ", TUCL2)
IICL2 = int (input ("Inventario Inicial: "))
UPCL2 = (TUCL2 - IICL2)
print ("Unidades a Producir: ", UPCL2)
print (" ")
print ("Producto CL Total 2016")
UVCLT = (UVCL1 + UVCL2)
print ("Unidades a Vender: ", UVCLT)
IFCLT = IFCL2
print ("Inventario Final: ", IFCLT)
TUCLT = (UVCLT + IFCLT)
print ("Total de Unidades: ", TUCLT)
IICLT = IICL1
print ("Inventario Inicial: ", IICLT) 
UPCLT = (UPCL1 + UPCL2)
print ("Unidades a Producir: ", UPCLT)
print (" ")
print ("-" * 60)
print (" ")
print ("Producto CE Primer Semestre")
UVCE1 = int (input ("Unidades a Vender: "))
IFCE1 = int (input ("Inventario Final: "))
TUCE1 = (UVCE1 + IFCE1)
print ("Total de Unidades: ", TUCE1)
IICE1 = int (input ("Inventario Inicial: "))
UPCE1 = (TUCE1 - IICE1)
print ("Unidades a Producir: ", UPCE1)
print (" ")
print ("Producto CE Segundo Semestre")
UVCE2 = int (input ("Unidades a Vender: "))
IFCE2 = int (input ("Inventario Final: "))
TUCE2 = (UVCE2 + IFCE2)
print ("Total de Unidades: ", TUCE2)
IICE2 = int (input ("Inventario Inicial: "))
UPCE2 = (TUCE2 - IICE2)
print ("Unidades a Producir: ", UPCE2)
print (" ")
print ("Producto CE Total 2016")
UVCET = (UVCE1 + UVCE2)
print ("Unidades a Vender: ", UVCET)
IFCET = IFCE2
print ("Inventario Final: ", IFCET)
TUCET = (UVCET + IFCET)
print ("Total de Unidades: ", TUCET)
IICET = IICE1
print ("Inventario Inicial: ", IICET) 
UPCET = (UPCE1 + UPCE2)
print ("Unidades a Producir: ", UPCET)
print (" ")
print ("-" * 60)
print (" ")
print ("Producto CR Primer Semestre")
UVCR1 = int (input ("Unidades a Vender: "))
IFCR1 = int (input ("Inventario Final: "))
TUCR1 = (UVCR1 + IFCR1)
print ("Total de Unidades: ", TUCR1)
IICR1 = int (input ("Inventario Inicial: "))
UPCR1 = (TUCR1 - IICR1)
print ("Unidades a Producir: ", UPCR1)
print (" ")
print ("Producto CR Segundo Semestre")
UVCR2 = int (input ("Unidades a Vender: "))
IFCR2 = int (input ("Inventario Final: "))
TUCR2 = (UVCR2 + IFCR2)
print ("Total de Unidades: ", TUCR2)
IICR2 = int (input ("Inventario Inicial: "))
UPCR2 = (TUCR2 - IICR2)
print ("Unidades a Producir: ", UPCR2)
print (" ")
print ("Producto CR Total 2016")
UVCRT = (UVCR1 + UVCR2)
print ("Unidades a Vender: ", UVCRT)
IFCRT = IFCR2
print ("Inventario Final: ", IFCRT)
TUCRT = (UVCRT + IFCRT)
print ("Total de Unidades: ", TUCRT)
IICRT = IICR1
print ("Inventario Inicial: ", IICRT) 
UPCRT = (UPCR1 + UPCR2)
print ("Unidades a Producir: ", UPCRT)
print (" ")
print ("-" * 63)
print ("")

#TABLA 4
print ("--- PRESUPUESTO DE REQUERIMIENTO DE MATERIALES ---")
print (" ")
print ("Producto CL primer semestre")
print (" ")
UPP_CL1 = int (input ("Unidades a Producir: "))
print (" ")
print ("Material A")
RMA_CL1 = float (input ("Requerimiento de Material: "))
TMAR_CL1 = (UPP_CL1 * RMA_CL1)
print ("Total de Material A requerido: ", TMAR_CL1)
print (" ")
print ("Material B")
RMB_CL1 = float (input ("Requerimiento de Material: "))
TMBR_CL1 = (UPP_CL1 * RMB_CL1)
print ("Total de Material B requerido: ", TMBR_CL1)
print (" ")
print ("Material C")
RMC_CL1 = float (input ("Requerimiento de Material: "))
TMCR_CL1 = (UPP_CL1 * RMC_CL1)
print ("Total de Material C requerido: ", TMCR_CL1)
print (" ")
print ("»")
print (" ")



print ("Producto CL segundo semestre")
print (" ")
UPP_CL2 = int (input ("Unidades a Producir: "))
print (" ")
print ("Material A")
RMA_CL2 = float (input ("Requerimiento de Material: "))
TMAR_CL2 = (UPP_CL2 * RMA_CL2)
print ("Total de Material A requerido: ", TMAR_CL2)
print (" ")
print ("Material B")
RMB_CL2 = float (input ("Requerimiento de Material: "))
TMBR_CL2 = (UPP_CL2 * RMB_CL2)
print ("Total de Material B requerido: ", TMBR_CL2)
print (" ")
print ("Material C")
RMC_CL2 = float (input ("Requerimiento de Material: "))
TMCR_CL2 = (UPP_CL2 * RMC_CL2)
print ("Total de Material C requerido: ", TMCR_CL2)
print (" ")
print ("»")
print (" ")

print ("Producto CL Total 2016")
print (" ")
UPP_CLT = (UPP_CL1 + UPP_CL2)
print ("Unidades a Producir: ", UPP_CLT)
print (" ")
print ("Material A")
RMA_CLT = float (input ("Requerimiento de Material: "))
TMAR_CLT = (UPP_CLT * RMA_CLT)
print ("Total de Material A requerido: ", TMAR_CLT)
print (" ")
print ("Material B")
RMB_CLT = float (input ("Requerimiento de Material: "))
TMBR_CLT = (UPP_CLT * RMB_CLT)
print ("Total de Material B requerido: ", TMBR_CLT)
print (" ")
print ("Material C")
RMC_CLT = float (input ("Requerimiento de Material: "))
TMCR_CLT = (UPP_CLT * RMC_CLT)
print ("Total de Material C requerido: ", TMCR_CLT)
print (" ")
print ("-" * 60)
print (" ")

print ("Producto CE primer semestre")
print (" ")
UPP_CE1 = int (input ("Unidades a Producir: "))
print (" ")
print ("Material A")
RMA_CE1 = float (input ("Requerimiento de Material: "))
TMAR_CE1 = (UPP_CE1 * RMA_CE1)
print ("Total de Material A requerido: ", TMAR_CE1)
print (" ")
print ("Material B")
RMB_CE1 = float (input ("Requerimiento de Material: "))
TMBR_CE1 = (UPP_CE1 * RMB_CE1)
print ("Total de Material B requerido: ", TMBR_CE1)
print (" ")
print ("Material C")
RMC_CE1 = float (input ("Requerimiento de Material: "))
TMCR_CE1 = (UPP_CE1 * RMC_CE1)
print ("Total de Material C requerido: ", TMCR_CE1)
print (" ")
print ("»")
print (" ")



print ("Producto CE segundo semestre")
print (" ")
UPP_CE2 = float (input ("Unidades a Producir: "))
print (" ")
print ("Material A")
RMA_CE2 = float (input ("Requerimiento de Material: "))
TMAR_CE2 = (UPP_CE2 * RMA_CE2)
print ("Total de Material A requerido: ", TMAR_CE2)
print (" ")
print ("Material B")
RMB_CE2 = float (input ("Requerimiento de Material: "))
TMBR_CE2 = (UPP_CE2 * RMB_CE2)
print ("Total de Material B requerido: ", TMBR_CE2)
print (" ")
print ("Material C")
RMC_CE2 = float (input ("Requerimiento de Material: "))
TMCR_CE2 = (UPP_CE2 * RMC_CE2)
print ("Total de Material C requerido: ", TMCR_CE2)
print (" ")
print ("»")
print (" ")

print ("Producto CE Total 2016")
print (" ")
UPP_CET = (UPP_CE1 + UPP_CE2)
print ("Unidades a Producir: ", UPP_CET)
print (" ")
print ("Material A")
RMA_CET = float (input ("Requerimiento de Material: "))
TMAR_CET = (UPP_CET * RMA_CET)
print ("Total de Material A requerido: ", TMAR_CET)
print (" ")
print ("Material B")
RMB_CET = float (input ("Requerimiento de Material: "))
TMBR_CET = (UPP_CET * RMB_CET)
print ("Total de Material B requerido: ", TMBR_CET)
print (" ")
print ("Material C")
RMC_CET = float (input ("Requerimiento de Material: "))
TMCR_CET = (UPP_CET * RMC_CET)
print ("Total de Material C requerido: ", TMCR_CET)
print (" ")
print ("-" * 60)
print (" ")

print ("Producto CR primer semestre")
print (" ")
UPP_CR1 = int (input ("Unidades a Producir: "))
print (" ")
print ("Material A")
RMA_CR1 = float (input ("Requerimiento de Material: "))
TMAR_CR1 = (UPP_CR1 * RMA_CR1)
print ("Total de Material A requerido: ", TMAR_CR1)
print (" ")
print ("Material B")
RMB_CR1 = float (input ("Requerimiento de Material: "))
TMBR_CR1 = (UPP_CR1 * RMB_CR1)
print ("Total de Material B requerido: ", TMBR_CR1)
print (" ")
print ("Material C")
RMC_CR1 = float (input ("Requerimiento de Material: "))
TMCR_CR1 = (UPP_CR1 * RMC_CR1)
print ("Total de Material C requerido: ", TMCR_CR1)
print (" ")
print ("»")
print (" ")



print ("Producto CR segundo semestre")
print (" ")
UPP_CR2 = int (input ("Unidades a Producir: "))
print (" ")
print ("Material A")
RMA_CR2 = float (input ("Requerimiento de Material: "))
TMAR_CR2 = (UPP_CR2 * RMA_CR2)
print ("Total de Material A requerido: ", TMAR_CR2)
print (" ")
print ("Material B")
RMB_CR2 = float (input ("Requerimiento de Material: "))
TMBR_CR2 = (UPP_CR2 * RMB_CR2)
print ("Total de Material B requerido: ", TMBR_CR2)
print (" ")
print ("Material C")
RMC_CR2 = float (input ("Requerimiento de Material: "))
TMCR_CR2 = (UPP_CR2 * RMC_CR2)
print ("Total de Material C requerido: ", TMCR_CR2)
print (" ")
print ("»")
print (" ")

print ("Producto CR Total 2016")
print (" ")
UPP_CRT = (UPP_CR1 + UPP_CR2)
print ("Unidades a Producir: ", UPP_CRT)
print (" ")
print ("Material A")
RMA_CRT = float (input ("Requerimiento de Material: "))
TMAR_CRT = (UPP_CRT * RMA_CRT)
print ("Total de Material A requerido: ", TMAR_CRT)
print (" ")
print ("Material B")
RMB_CRT = float (input ("Requerimiento de Material: "))
TMBR_CRT = (UPP_CRT * RMB_CRT)
print ("Total de Material B requerido: ", TMBR_CRT)
print (" ")
print ("Material C")
RMC_CRT = float (input ("Requerimiento de Material: "))
TMCR_CRT = (UPP_CRT * RMC_CRT)
print ("Total de Material C requerido: ", TMCR_CRT)
print (" ")
print ("-" * 60)
print (" ")

print ("Total de Requerimientos primer semestre")
TR_MA1 = (TMAR_CL1 + TMAR_CE1 + TMAR_CR1)
print ("Material A: ", TR_MA1)
TR_MB1 = (TMBR_CL1 + TMBR_CE1 + TMBR_CR1)
print ("Material B: ", TR_MB1)
TR_MC1 = (TMCR_CL1 + TMCR_CE1 + TMCR_CR1)
print ("Material C: ", TR_MC1)
print (" ")
print ("-" * 60)
print (" ")

print ("Total de Requerimientos segundo semestre")
TR_MA2 = (TMAR_CL2 + TMAR_CE2 + TMAR_CR2)
print ("Material A: ", TR_MA2)
TR_MB2 = (TMBR_CL2 + TMBR_CE2 + TMBR_CR2)
print ("Material B: ", TR_MB2)
TR_MC2 = (TMCR_CL2 + TMCR_CE2 + TMCR_CR2)
print ("Material C: ", TR_MC2)
print (" ")
print ("-" * 60)
print (" ")

print ("Total de Requerimientos Total 2016")
TR_MAT = (TMAR_CLT + TMAR_CET + TMAR_CRT)
print ("Material A: ", TR_MAT)
TR_MBT = (TMBR_CLT + TMBR_CET + TMBR_CRT)
print ("Material B: ", TR_MBT)
TR_MCT = (TMCR_CLT + TMCR_CET + TMCR_CRT)
print ("Material C: ", TR_MCT)
print (" ")
print ("-" * 60)
print (" ")

#TABLA 5
print ("--- PRESUPUESTO DE COMPRA DE MATERIALES ---")
print (" ")
print ("Material A primer semestre")
print (" ")
print ("Requerimiento de materiales: ", TR_MA1)
IF_MA1 = float (input ("Inventario Final: "))
TM_MA1 = (TR_MA1 + IF_MA1)
print ("Total de Materiales: ", TM_MA1)
II_MA1 = float (input ("Inventario Inicial: "))
MC_MA1 = (TM_MA1 - II_MA1)
print ("Material a Comprar: ", MC_MA1)
PC_MA1 = float (input ("Precio de compra: "))
T_MAD1 = (MC_MA1 * PC_MA1)
print ("Total de Material A en $ en el primer semestre: ", T_MAD1)
print (" ")
print ("»")
print (" ")
print ("Material A segundo semestre")
print (" ")
print ("Requerimiento de materiales: ", TR_MA2)
IF_MA2 = float (input ("Inventario Final: "))
TM_MA2 = (TR_MA2 + IF_MA2)
print ("Total de Materiales: ", TM_MA2)
II_MA2 = float (input ("Inventario Inicial: "))
MC_MA2 = (TM_MA2 - II_MA2)
print ("Material a Comprar: ", MC_MA2)
PC_MA2 = float (input ("Precio de compra: "))
T_MAD2 = (MC_MA2 * PC_MA2)
print ("Total de Material A en $ en el segundo semestre: ", T_MAD2)
print (" ")
print ("»")
print (" ")
print ("Material A Total 2016")
print (" ")
print ("Requerimiento de materiales: ", TR_MAT)
IF_MAT = float (input ("Inventario Final: "))
TM_MAT = (TR_MAT + IF_MAT)
print ("Total de Materiales: ", TM_MAT)
II_MAT = float (input ("Inventario Inicial: "))
MC_MAT = (TM_MAT - II_MAT)
print ("Material a Comprar: ", MC_MAT)
T_MADT = (T_MAD1 + T_MAD2)
print ("Total en Material A en $ en total del año: ", T_MADT)
print (" ")
print ("-" * 60)
print (" ")

print ("Material B primer semestre")
print (" ")
print ("Requerimiento de materiales: ", TR_MB1)
IF_MB1 = float (input ("Inventario Final: "))
TM_MB1 = (TR_MB1 + IF_MB1)
print ("Total de Materiales: ", TM_MB1)
II_MB1 = float (input ("Inventario Inicial: "))
MC_MB1 = (TM_MB1 - II_MB1)
print ("Material a Comprar: ", MC_MB1)
PC_MB1 = float (input ("Precio de compra: "))
T_MBD1 = (MC_MB1 * PC_MB1)
print ("Total de Material B en $ en el primer semestre: ", T_MBD1)
print (" ")
print ("»")
print (" ")
print ("Material B segundo semestre")
print (" ")
print ("Requerimiento de materiales: ", TR_MB2)
IF_MB2 = float (input ("Inventario Final: "))
TM_MB2 = (TR_MB2 + IF_MB2)
print ("Total de Materiales: ", TM_MB2)
II_MB2 = float (input ("Inventario Inicial: "))
MC_MB2 = (TM_MB2 - II_MB2)
print ("Material a Comprar: ", MC_MB2)
PC_MB2 = float (input ("Precio de compra: "))
T_MBD2 = (MC_MB2 * PC_MB2)
print ("Total de Material B en $ en el segundo semestre: ", T_MBD2)
print (" ")
print ("»")
print (" ")
print ("Material B Total 2016")
print (" ")
print ("Requerimiento de materiales: ", TR_MBT)
IF_MBT = float (input ("Inventario Final: "))
TM_MBT = (TR_MBT + IF_MBT)
print ("Total de Materiales: ", TM_MBT)
II_MBT = float (input ("Inventario Inicial: "))
MC_MBT = (TM_MBT - II_MBT)
print ("Material a Comprar: ", MC_MBT)
T_MBDT = (T_MBD1 + T_MBD2)
print ("Total en Material A en $ en total del año: ", T_MBDT)
print (" ")
print ("-" * 60)
print (" ")

print ("Material C primer semestre")
print (" ")
print ("Requerimiento de materiales: ", TR_MC1)
IF_MC1 = float (input ("Inventario Final: "))
TM_MC1 = (TR_MC1 + IF_MC1)
print ("Total de Materiales: ", TM_MC1)
II_MC1 = float (input ("Inventario Inicial: "))
MC_MC1 = (TM_MC1 - II_MC1)
print ("Material a Comprar: ", MC_MC1)
PC_MC1 = float (input ("Precio de compra: "))
T_MCD1 = (MC_MC1 * PC_MC1)
print ("Total de Material C en $ en el primer semestre: ", T_MCD1)
print (" ")
print ("»")
print (" ")
print ("Material C segundo semestre")
print (" ")
print ("Requerimiento de materiales: ", TR_MC2)
IF_MC2 = float (input ("Inventario Final: "))
TM_MC2 = (TR_MC2 + IF_MC2)
print ("Total de Materiales: ", TM_MC2)
II_MC2 = float (input ("Inventario Inicial: "))
MC_MC2 = (TM_MC2 - II_MC2)
print ("Material a Comprar: ", MC_MC2)
PC_MC2 = float (input ("Precio de compra: "))
T_MCD2 = (MC_MC2 * PC_MC2)
print ("Total de Material C en $ en el segundo semestre: ", T_MCD2)
print (" ")
print ("»")
print (" ")
print ("Material C Total 2016")
print (" ")
print ("Requerimiento de materiales: ", TR_MCT)
IF_MCT = float (input ("Inventario Final: "))
TM_MCT = (TR_MCT + IF_MCT)
print ("Total de Materiales: ", TM_MCT)
II_MCT = float (input ("Inventario Inicial: "))
MC_MCT = (TM_MCT - II_MCT)
print ("Material a Comprar: ", MC_MCT)
T_MCDT = (T_MCD1 + T_MCD2)
print ("Total en Material C en $ en total del año: ", T_MCDT)
print (" ")
print ("-" * 60)
print (" ")

CT_S1 = (T_MAD1 + T_MBD1 + T_MCD1)
print ("Compras totales en el primer semestre: ", CT_S1)
CT_S2 = (T_MAD2 + T_MBD2 + T_MCD2)
print ("Compras totales en el segundo semestre: ", CT_S2)
CT_TA = (T_MADT + T_MBDT + T_MCDT)
print ("Compras totales en el segundo semestre: ", CT_TA)
print (" ")
print ("-" * 63)
print (" ")

#TABLA 6
print ("--- DETERMINACION DEL SALDO DE PROVEEDORES Y FLUJO DE SALIDAS ---")
SaldoProveedores = int (input ("Saldo de Proveedores 31-dic-2015: "))
print ("Compras 2016: ",  CT_TA)
TotalP2016 = (SaldoProveedores + CT_TA)
print (" ")
print ("Total de Proveedores 2016: ", TotalP2016)
print (" ")
print ("Salidas de efectivo: ")
Proveedores2015 = int (input ("Por Proveedores del 2015: "))
Proveedores2016 = (CT_TA * .5)
print ("Por Proveedores del 2016: ", Proveedores2016)
print (" ")
TotalSalidas2016 = (Proveedores2015 + Proveedores2016)
print ("Total de Salidas 2016: ", TotalSalidas2016)
print (" ")
SaldoProveedores2016 = (TotalP2016 - TotalSalidas2016)
print ("Saldo de Proveedoores del 2016: ", SaldoProveedores2016)
print (" ")
print ("-" * 63)
print (" ")

#TABLA 7
print ("--- PRESUPUESTO DE MANO DE OBRA DIRECTA ---")
print (" ")
print ("Producto CL en primer semestre")
print ("Unidades a producir: ", UPCL1)
HRU_CL1 = float (input ("Horas requeridas por unidad: "))
THR_CL1 = (UPCL1 * HRU_CL1)
print ("Total de horas requeridas: ", THR_CL1)
CH_CL1 = int (input ("Cuota por hora: "))
IMOD_CL1 = (THR_CL1 * CH_CL1)
print ("Importe de M.O.D.:", IMOD_CL1)
print (" ")

print ("Producto CL en segundo semestre")
print ("Unidades a producir: ", UPCL2)
HRU_CL2 = float (input ("Horas requeridas por unidad: "))
THR_CL2 = (UPCL2 * HRU_CL2)
print ("Total de horas requeridas: ", THR_CL2)
CH_CL2 = int (input ("Cuota por hora: "))
IMOD_CL2 = (THR_CL2 * CH_CL2)
print ("Importe de M.O.D.:", IMOD_CL2)
print (" ")

print ("Producto CL total en el año")
print ("Unidades a producir: ", UPCLT)
HRU_CLT = float (input ("Horas requeridas por unidad: "))
THR_CLT = (UPCLT * HRU_CLT)
print ("Total de horas requeridas: ", THR_CLT)
IMOD_CLT = (IMOD_CL1 + IMOD_CL2)
print ("Importe de M.O.D.:", IMOD_CLT)
print (" ")
print ("-" * 63)
print (" ")

print ("Producto CE en primer semestre")
print ("Unidades a producir: ", UPCE1)
HRU_CE1 = float (input ("Horas requeridas por unidad: "))
THR_CE1 = (UPCE1 * HRU_CE1)
print ("Total de horas requeridas: ", THR_CE1)
CH_CE1 = int (input ("Cuota por hora: "))
IMOD_CE1 = (THR_CE1 * CH_CE1)
print ("Importe de M.O.D.:", IMOD_CE1)
print (" ")

print ("Producto CE en segundo semestre")
print ("Unidades a producir: ", UPCE2)
HRU_CE2 = float (input ("Horas requeridas por unidad: "))
THR_CE2 = (UPCE2 * HRU_CE2)
print ("Total de horas requeridas: ", THR_CE2)
CH_CE2 = int (input ("Cuota por hora: "))
IMOD_CE2 = (THR_CE2 * CH_CE2)
print ("Importe de M.O.D.:", IMOD_CE2)
print (" ")

print ("Producto CE total en el año")
print ("Unidades a producir: ", UPCET)
HRU_CET = float (input ("Horas requeridas por unidad: "))
THR_CET = (UPCET * HRU_CET)
print ("Total de horas requeridas: ", THR_CET)
IMOD_CET = (IMOD_CE1 + IMOD_CE2)
print ("Importe de M.O.D.:", IMOD_CET)
print (" ")
print ("-" * 63)
print (" ")

print ("Producto CR en primer semestre")
print ("Unidades a producir: ", UPCR1)
HRU_CR1 = float (input ("Horas requeridas por unidad: "))
THR_CR1 = (UPCR1 * HRU_CR1)
print ("Total de horas requeridas: ", THR_CR1)
CH_CR1 = int (input ("Cuota por hora: "))
IMOD_CR1 = (THR_CR1 * CH_CR1)
print ("Importe de M.O.D.:", IMOD_CR1)
print (" ")

print ("Producto CR en segundo semestre")
print ("Unidades a producir: ", UPCR2)
HRU_CR2 = float (input ("Horas requeridas por unidad: "))
THR_CR2 = (UPCR2 * HRU_CR2)
print ("Total de horas requeridas: ", THR_CR2)
CH_CR2 = int (input ("Cuota por hora: "))
IMOD_CR2 = (THR_CR2 * CH_CR2)
print ("Importe de M.O.D.:", IMOD_CR2)
print (" ")

print ("Producto CR total en el año")
print ("Unidades a producir: ", UPCRT)
HRU_CRT = float (input ("Horas requeridas por unidad: "))
THR_CRT = (UPCRT * HRU_CRT)
print ("Total de horas requeridas: ", THR_CRT)
IMOD_CRT = (IMOD_CR1 + IMOD_CR2)
print ("Importe de M.O.D.:", IMOD_CRT)
print (" ")
print ("-" * 63)
print (" ")

THR_S1 = (THR_CL1 + THR_CE1 + THR_CR1)
print ("Total de horas requeridas por semestre en primer semestre: ", THR_S1)
THR_S2 = (THR_CL2 + THR_CE2 + THR_CR2)
print ("Total de horas requeridas por semestre en segundo semestre: ", THR_S2)
THR_TA = (THR_CLT + THR_CET + THR_CRT)
print ("Total de horas requeridas en el año: ", THR_TA)
print (" ")
print ("»")
print (" ")

TMOD_S1 = (IMOD_CL1 + IMOD_CE1 + IMOD_CR1)
print ("Total de M.O.D. por semestre en primer semestre: ", TMOD_S1)
TMOD_S2 = (IMOD_CL2 + IMOD_CE2 + IMOD_CR2)
print ("Total de M.O.D. por semestre en segundo semestre: ", TMOD_S2)
TMOD_T = (IMOD_CLT + IMOD_CET + IMOD_CRT)
print ("Total de M.O.D. por año: ", TMOD_T)
print (" ")
print ("-" * 63)
print (" ")

#TABLA 8
print ("--- PRESUPUESTO DE GASTOS INDIRECTOS DE FABRICACION ---")
print (" ")
Dep_GI1 = float (input ("Depreciación en primer semestre: "))
Dep_GI2 = float (input ("Depreciación en segundo semestre: "))
Dep_GIT = (Dep_GI1 + Dep_GI2)
print ("Depreciación en total del año: ", Dep_GIT)
print (" ")
Seg_GI1 = float (input ("Seguros en primer semestre: "))
Seg_GI2 = float (input("Seguros en segundo semestre: "))
Seg_GIT = (Seg_GI1 + Seg_GI2)
print ("Seguros en el año: ", Seg_GIT)
print (" ")
Man_GI1 = float (input ("Mantenimiento en primer semestre: "))
Man_GI2 = float (input ("Mantenimiento en segundo semestre: "))
Man_GIT = (Man_GI1 + Man_GI2)
print ("Mantenimiento en el año: ", Man_GIT)
print (" ")
Eneg_GI1 = float (input ("Energéticos en primer semestre: "))
Eneg_GI2 = float (input ("Energéticos en segundo semestre: "))
Eneg_GIT = (Eneg_GI1 + Eneg_GI2)
print ("Energéticos en el año: ", Eneg_GIT)
print (" ")
Varios_GI1 = float (input ("Varios en primer semestre: "))
Varios_GI2 = float (input ("Varios en segundo semestre: "))
Varios_GIT = (Varios_GI1 + Varios_GI2)
print ("Varios en el año: ", Varios_GIT)
print (" ")
print ("-")
print (" ")
T_GIFS1 = (Dep_GI1 + Seg_GI1 + Man_GI1 + Eneg_GI1 + Varios_GI1)
print ("Total G.I.F en primer semestre: ", T_GIFS1)
T_GIFS2 = (Dep_GI2 + Seg_GI2 + Man_GI2 + Eneg_GI2 + Varios_GI2)
print ("Total G.I.F en segundo semestre: ", T_GIFS2)
T_GIFST = (Dep_GIT + Seg_GIT + Man_GIT + Eneg_GIT + Varios_GIT)
print ("Total G.I.F en el año: ", T_GIFST)
print (" ")
print ("»")
print (" ")
print ("Coeficiente para determinar el costo por hora de Gastos Indirectos de Fabricación")
print ("Total de G.I.F: ", T_GIFST)
print ("(/) Total horas M.O.D. Anual: ", THR_TA)
CH_GIF = (T_GIFST / THR_TA)
print ("(=) Costo por Hora de G.I.F: ", CH_GIF)
print (" ")
print ("-" * 63)
print (" ")

#TABLA 9
print ("--- PRESUPUESTO DE GASTOS DE OPERACION ---")
print (" ")
Dep_GO1 = float (input ("Depreciación en primer semestre: "))
Dep_GO2 = float (input ("Depreciación en segundo semestre: "))
Dep_GOT = (Dep_GO1 + Dep_GO2)
print ("Depreciación en total del año: ", Dep_GOT)
print (" ")
SS_GO1 = float (input ("Sueldos y salarios en primer semestre: "))
SS_GO2 = float (input("Sueldos y salarios en segundo semestre: "))
SS_GOT = (SS_GO1 + SS_GO2)
print ("Sueldos y salarios en el año: ", SS_GOT)
print (" ")
Com_GO1 = float (input ("Comisiones en primer semestre: "))
Com_GO2 = float (input ("Comisiones en segundo semestre: "))
Com_GOT = (Com_GO1 + Com_GO2)
print ("Comisiones en el año: ", Com_GOT)
print (" ")
Varios_GO1 = float (input ("Varios en primer semestre: "))
Varios_GO2 = float (input ("Varios en segundo semestre: "))
Varios_GOT = (Varios_GO1 + Varios_GO2)
print ("Varios en el año: ", Varios_GOT)
print (" ")
IO_GO1 = float (input ("Intereses por obligaciones en primer semestre: "))
IO_GO2 = float (input ("Intereses por obligaciones en segundo semestre: "))
IO_GOT = (IO_GO1 + IO_GO2)
print ("Intereses por obligaciones en el año: ", IO_GOT)
print (" ")
print ("-")
print (" ")
T_GOS1 = (Dep_GO1 + SS_GO1 + Com_GO1 + Varios_GO1 + IO_GO1)
print ("Total de Gastos de Operación en primer semestre: ", T_GOS1)
T_GOS2 = (Dep_GO2 + SS_GO2 + Com_GO2 + Varios_GO2 + IO_GO2)
print ("Total de Gastos de Operación en segundo semestre: ", T_GOS2)
T_GOT = (Dep_GOT + SS_GOT + Com_GOT + Varios_GOT + IO_GOT)
print ("Total de Gastos de Operación en el año: ", T_GOT)
print (" ")
print ("»")
print (" ")

#TABLA 10
print ("--- DETERMINACION DEL COSTO UNITARIO DE PRODUCTOS TERMINADOS ---")
print (" ")
print ("Producto CL")
print ("Costo Material A: ", PC_MA2)
print ("Costo Material B: ", PC_MB2)
print ("Costo Material C: ", PC_MC2)
MO_CL = CH_CL2
print ("Costo de Mano de Obra: ", MO_CL)
GIF_CL = CH_GIF
print ("Costo de Gastos Indirectos de Fabricación: ", GIF_CL)
print (" ")

CMA_CL = float (input("Cantidad de Material A: "))
CMB_CL = float (input ("Cantidad de Material B: "))
CMC_CL = float (input ("Cantidad de Material C: "))
CMO_CL = float (input ("Cantidad de Mano de Obra: "))
CGIF_CL = CMO_CL
print ("Cantidad de Gastos Indirectos de Fabricación: ", CGIF_CL)
print (" ")

CU_MACL = (PC_MA2 * CMA_CL)
print ("Costo Unitario Material A: ", CU_MACL)
CU_MBCL = (PC_MB2 * CMB_CL)
print ("Costo Unitario Material B: ", CU_MBCL)
CU_MCCL = (PC_MC2 * CMC_CL)
print ("Costo Unitario Material C: ", CU_MCCL)
CU_MOCL = (MO_CL * CMO_CL)
print ("Costo Unitario de Mano de Obra: ", CU_MOCL)
CU_GIFCL = (GIF_CL * CMO_CL)
print ("Costo Unitario Material B: ", CU_GIFCL)
CU_CL = (CU_MACL + CU_MBCL + CU_MCCL + CU_MOCL + CU_GIFCL)
print ("Costo Unitario: ", CU_CL)
print (" ")
print ("-" * 63)
print (" ")

print ("Producto CE")
print ("Costo Material A: ", PC_MA2)
print ("Costo Material B: ", PC_MB2)
print ("Costo Material C: ", PC_MC2)
MO_CE = CH_CE2
print ("Costo de Mano de Obra: ", MO_CE)
GIF_CE = CH_GIF
print ("Costo de Gastos Indirectos de Fabricación: ", GIF_CE)
print (" ")

CMA_CE = float (input("Cantidad de Material A: "))
CMB_CE = float (input ("Cantidad de Material B: "))
CMC_CE = float (input ("Cantidad de Material C: "))
CMO_CE = float (input ("Cantidad de Mano de Obra: "))
CGIF_CE = CMO_CE
print ("Cantidad de Gastos Indirectos de Fabricación: ", CGIF_CE)
print (" ")

CU_MACE = (PC_MA2 * CMA_CE)
print ("Costo Unitario Material A: ", CU_MACE)
CU_MBCE = (PC_MB2 * CMB_CE)
print ("Costo Unitario Material B: ", CU_MBCE)
CU_MCCE = (PC_MC2 * CMC_CE)
print ("Costo Unitario Material C: ", CU_MCCE)
CU_MOCE = (MO_CE * CMO_CE)
print ("Costo Unitario de Mano de Obra: ", CU_MOCE)
CU_GIFCE = (GIF_CE * CMO_CE)
print ("Costo Unitario Material B: ", CU_GIFCE)
CU_CE = (CU_MACE + CU_MBCE + CU_MCCE + CU_MOCE + CU_GIFCE)
print ("Costo Unitario: ", CU_CE)
print (" ")
print ("-" * 63)
print (" ")

print ("Producto CR")
print ("Costo Material A: ", PC_MA2)
print ("Costo Material B: ", PC_MB2)
print ("Costo Material C: ", PC_MC2)
MO_CR = CH_CR2
print ("Costo de Mano de Obra: ", MO_CR)
GIF_CR = CH_GIF
print ("Costo de Gastos Indirectos de Fabricación: ", GIF_CR)
print (" ")

CMA_CR = float (input("Cantidad de Material A: "))
CMB_CR = float (input ("Cantidad de Material B: "))
CMC_CR = float (input ("Cantidad de Material C: "))
CMO_CR = float (input ("Cantidad de Mano de Obra: "))
CGIF_CR = CMO_CR
print ("Cantidad de Gastos Indirectos de Fabricación: ", CGIF_CR)
print (" ")

CU_MACR = (PC_MA2 * CMA_CR)
print ("Costo Unitario Material A: ", CU_MACR)
CU_MBCR = (PC_MB2 * CMB_CR)
print ("Costo Unitario Material B: ", CU_MBCR)
CU_MCCR = (PC_MC2 * CMC_CR)
print ("Costo Unitario Material C: ", CU_MCCR)
CU_MOCR = (MO_CR * CMO_CR)
print ("Costo Unitario de Mano de Obra: ", CU_MOCR)
CU_GIFCR = (GIF_CR * CMO_CR)
print ("Costo Unitario Material B: ", CU_GIFCR)
CU_CR = (CU_MACR + CU_MBCR + CU_MCCR + CU_MOCR + CU_GIFCR)
print ("Costo Unitario: ", CU_CR)
print (" ")
print ("-" * 63)
print (" ")
print (" ")

#TABLA 11
print ("--- VALUACIÓN DE INVENTARIOS FINALES ---")
print (" ")
print ("Inventario Final de Materiales")
print (" ")
print ("Unidades de Material A: ", IF_MA2)
print ("Unidades de Material B: ", IF_MB2)
print ("Unidades de Material C: ", IF_MC2)
print (" ")
print ("Costo Unitario de Material A: ", PC_MA2)
print ("Costo Unitario de Material B: ", PC_MB2)
print ("Costo Unitario de Material C: ", PC_MC2)
print (" ")
IFM_MACT = (IF_MA2 * PC_MA2)
print ("Costo Total de Material A: ", IFM_MACT)
IFM_MBCT = (IF_MB2 * PC_MB2)
print ("Costo Total de Material B: ", IFM_MBCT)
IFM_MCCT = (IF_MC2 * PC_MC2)
print ("Costo Total de Material C: ", IFM_MCCT)
print (" ")
IFM_CT = (IFM_MACT + IFM_MBCT + IFM_MCCT)
print ("Inventario Final de Materiales: ", IFM_CT)
print (" ")
print ("-" * 63)
print (" ")
print ("Inventario Final de Producto Terminado")
print (" ")
print ("Unidades Producto CL: ", IFCL2)
print ("Unidades Producto CE: ", IFCE2)
print ("Unidades Producto CR: ", IFCR2)
print (" ")
print ("Costo Unitario de Producto CL: ", CU_CL)
print ("Costo Unitario de Producto CE: ", CU_CE)
print ("Costo Unitario de Producto CR: ", CU_CR)
print (" ")
IFPT_CLCT = (IFCL2 * CU_CL)
print ("Costo Total de Producto CL: ", IFPT_CLCT)
IFPT_CECT = (IFCE2 * CU_CE)
print ("Costo Total de Producto CE: ", IFPT_CECT)
IFPT_CRCT = (IFCR2 * CU_CR)
print ("Costo Total de Producto CR: ", IFPT_CRCT)
print (" ")
IFPT_CT = (IFPT_CLCT + IFPT_CECT + IFPT_CRCT)
print ("Inventario Final de Producto Terminado: ", IFPT_CT)
print (" ")

#II. PRESUPUESTO FINANCIERO
print ("II. PRESUPUESTO FINANCIERO")
print (" ")
print ("MAQUILADOS MEXICANOS, S.A. DE C.V.")
print ("Estado de Costo de Producción y Ventas")
print ("Presupuesto del 1 de Enero al 31 de Diciembre del 2016")
print (" ")
SIM = int (input ("Saldo Inicial de Materiales: "))
print ("(+) Compras de Materiales: ", CT_TA)
MD = (SIM + CT_TA)
print ("(=) Material Disponible: ", MD)
print ("(-) Inventario Final de Materiales: ", IFM_CT)
MU = (MD - IFM_CT)
print ("(=) Materiales Utilizados: ", MU)
print ("(+) Mano de Obra Directa: ", TMOD_T)
print ("(+) Gastos de Fabricación Indirectos: ", T_GIFST)
CP = (MU + TMOD_T + T_GIFST)
print ("(=) Costo de Producción: ", CP)
II_PT = int (input ("(+) Inventario Inicial de Productos Terminados: "))
T_PD = (CP + II_PT)
print ("(=) Total de Producción Disponible: ", T_PD)
print ("(-) Inventario Final de Productos Terminados: ", IFPT_CT)
CV = (T_PD - IFPT_CT)
print ("(=) Costo de Ventas: ", CV)
print (" ")
print ("-" * 63)
print (" ")
print ("MAQUILADOS MEXICANOS, S.A. DE C.V.")
print ("Estados de Resultados")
print ("Presupuesto del 1 de Enero al 31 de Diciembre del 2016")
print (" ")
print ("Ventas: ", TVS)
print ("(-) Costo de Ventas: ", CV)
UB = (TVS - CV)
print ("(=) Utilidad Bruta: ", UB)
print ("(-) Gastos de Operación: ", T_GOT)
UO = (UB - T_GOT)
print ("(=) Utilidad de Operación: ", UO)
ISR = int (input ("(-) ISR: "))
PTU = int (input ("(-) PTU: "))
U_N = (UO - ISR - PTU)
print ("(=) Utilidad Neta: ", U_N)
print (" ")
print ("-" * 63)
print (" ")
print ("MAQUILADOS MEXICANOS, S.A. DE C.V.")
print ("Estado de Flujo de Efectivo")
print ("Presupuesto del 1 de Enero al 31 de Diciembre del 2016")
SI_E = int (input ("Saldo Inicial de Efectivo: "))
print ("Entradas: ")
print ("Cobranza 2016: ", Cobranza2016)
print ("Cobranza 2015: ", Cobranza2015)
T_E = (Cobranza2016 + Cobranza2015)
print ("Total de Entradas: ", T_E)
ED = (SI_E + T_E)
print ("Efectivo Disponible: ", ED)
print ("Salidas: ")
print ("Proveedores 2016: ", Proveedores2016)
print ("Proveedores 2015: ", Proveedores2015)
print ("Pago Mano de Obra Directa: ", TMOD_T)
PGIF = (T_GIFST - Dep_GIT)
print ("Pago Gastos Indirectos de Fabricación: ", PGIF)
PGO = (T_GOT - Dep_GOT)
print ("Pago Gastos de Operación: ", PGO)
C_AF = int (input ("Compra de Activo Fijo (Maquinaria): "))
P_ISR2015 = int (input ("Pago ISR 2015: "))
P_ISR2016 = int (input ("Pago ISR 2016: "))
T_S = (Proveedores2016 + Proveedores2015 + TMOD_T + PGIF + PGO + C_AF + P_ISR2015 + P_ISR2016) 
print ("Total de Salidas: ", T_S)
FE_A = (ED - T_S)
print ("Flujo de Efectivo Actual: ", FE_A)
print (" ")
print ("-" * 63)
print (" ")

print ("MAQUILADOS MEXICANOS, S.A. DE C.V.")
print ("Balance General")
print ("Presupuesto al 31 de diciembre del 2016")
print (" ")
print ("ACTIVO")
print ("Circulante")
print ("Efectivo: ", FE_A)
print ("Clientes: ", SaldoClientes2016)
DD = int (input ("Deudores Diversos: "))
FyE = int (input ("Funcionarios y Empleados: "))
print ("Inventario de Materiales: ", IFM_CT)
print ("Inventario de Producto Terminado: ", IFPT_CT)
T_AC = (FE_A + SaldoClientes2016 + DD + FyE + IFM_CT + IFPT_CT)
print ("Total de Activos Circulantes: ", T_AC)
print (" ")
print ("-" * 63)
print (" ")
print ("No Circulante")
Terreno = int (input ("Terreno: "))
PlantaEquipo = int (input ("Planta y Equipo: "))
Dep_Acm = int (input ("Depreciación Acumulada: "))
T_ANC = (Terreno + PlantaEquipo - Dep_Acm)
print ("Total Activos No Circulante: ", T_ANC)
print (" ")
A_T = (T_AC + T_ANC)
print ("ACTIVO TOTAL: ", A_T)
print (" ")
print ("-" * 63)
print (" ")
print ("PASIVO")
print ("Corto Plazo")
print ("Proveedores: ", SaldoProveedores2016)
DP = int (input ("Documentos por pagar: "))
ISR_P = int (input ("ISR por Pagar: "))
print ("PTU por Pagar: ", PTU)
TP_CP = (SaldoProveedores2016 + DP + ISR_P + PTU)
print ("Total de Pasivo Corto Plazo: ", TP_CP)
print (" ")
print ("-" * 63)
print (" ")
print ("Largo Plazo")
P_Ban = int (input ("Préstamos bancarios: "))
print ("Total de Pasivo Largo Plazo: ", P_Ban)
print (" ")
P_T = (TP_CP + P_Ban)
print ("PASIVO TOTAL", P_T)
print (" ")
print ("CAPITAL CONTABLE")
Cap_C = int (input ("Capital Contribuido: "))
Cap_G = int (input ("Capital Ganado: "))
print ("Utilidad del Ejercicio: ", U_N)
T_CapC = (Cap_C + Cap_G + U_N)
print ("Total de Capital Contable: ", T_CapC)
print (" ")
S_PyC = (P_T + T_CapC)
print ("SUMA DE PASIVO Y CAPITAL: ", S_PyC)
